import Head from 'next/head'

const Home = () => {
  return (
    <div>
      <Head>
        <title>Our Budget</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:text-white">
        Home
      </main>
    </div>
  )
}

export default Home

